<?php

namespace KwejkBundle\Repository;

/**
 * ObrazekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObrazekRepository extends \Doctrine\ORM\EntityRepository
{
}
