<?php

namespace KwejkBundle\Repository;

/**
 * OcenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcenaRepository extends \Doctrine\ORM\EntityRepository
{
}
